/*
 * This Java source file was generated by the Gradle 'init' task.
 */


package wordgame;
import wordgame.model.Guesser;
import wordgame.model.SecretWord;


public class Game {

    String word;
    Guesser guest;
    protected int errorLimit = 3;
    protected int numErrors = 0;
    private SecretWord guess;
    StringBuilder guessed_words;
    
    public Game(SecretWord secret,Guesser guessing){
        word = secret.getSecretWord();
        guessed_words = new StringBuilder(secret.word_withEmptySpaces());
        guest = guessing;
        guess = secret;
    }
    
    public void play(){
       
        boolean found;
        
        while(!guess.isFull(guessed_words) && this.numErrors < this.errorLimit)
        {            
            char letter = guest.getNextGuess(); 
            System.out.print("You entered ");
            System.out.println(letter);
            
            found = guessedLetters(letter);
                if(found)
                {
                    System.out.println("You guessed correctly");
                }
                else if(!found) 
                {
                    System.out.println("You already guessed " + letter + ", try another letter");
                }
                else
                {
                    this.numErrors = this.numErrors + 1;
                    System.out.println("No such letter in this word");
                    System.out.printf("You made ");
                    System.out.print(this.numErrors);
                    System.out.println(" mistakes");
                }
                
            //System.out.println("You guessed correctly");
            String temp = guessed_words.toString();
            guess.word_withChar(temp);    
            }
            
        }

    public Result getResult(){
        if(guess.isFull(guessed_words)){
            System.out.println("YOU "+Result.WIN);
            return Result.WIN;
        }
        else{
            System.out.println("YOU "+Result.LOSE);
            return Result.LOSE;
        } 
    }

    public void setErrorLimit(int errorLimit){
        this.errorLimit = errorLimit;
    }

    
    public boolean guessedLetters(char letter) {
        boolean found = false;
        char letter_LowerCase = Character.toLowerCase(letter);
        String word_LowerCase = word.toLowerCase();
        String eWord = guessed_words.toString();
        for (int i = 0; i < word.length(); i++) {
            if (letter_LowerCase == word_LowerCase.charAt(i) && letter_LowerCase != eWord.charAt(i)) {
                guessed_words.setCharAt(i, word.charAt(i));
                found = true;
            }
            else if (letter_LowerCase == word_LowerCase.charAt(i) && letter_LowerCase == eWord.charAt(i) )
            {
                found = false;
            }
        }
        
        return found;
    }

}

