/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package wordgame;

import org.junit.Test;
import static org.junit.Assert.*;

import wordgame.model.SecretWord;

public class GameTest {
    @Test public void playToWin() {
        SecretWord secret = new SecretWord("mouse");
        TestGuesser guesser = new TestGuesser("mouse");
        Game game = new Game(secret, guesser);
        game.play();
        assertEquals(game.getResult(), Result.WIN);
    }

    @Test public void playToLose() {
        SecretWord secret = new SecretWord("mouse");
        TestGuesser guesser = new TestGuesser("abcdf");
        Game game = new Game(secret, guesser);
        game.play();
        assertEquals(game.getResult(), Result.LOSE);
    }

    @Test public void errorLimitTestLose() {
        SecretWord secret = new SecretWord("mouse");
        TestGuesser guesser = new TestGuesser("abcdfgmouse");
        Game game = new Game(secret, guesser);
        game.setErrorLimit(6);
        game.play();
        assertEquals(game.getResult(), Result.LOSE);
    }

    @Test public void errorLimitTestWin() {
        SecretWord secret = new SecretWord("hello");
        TestGuesser guesser = new TestGuesser("abcdfghelo");
        Game game = new Game(secret, guesser);
        game.setErrorLimit(7);
        game.play();
        assertEquals(game.getResult(), Result.WIN);
    }
    @Test public void testUppercaseSecretGuessLowercase() {
        SecretWord secret = new SecretWord("PHONE");
        TestGuesser guesser = new TestGuesser("phone");
        Game game = new Game(secret, guesser);
        game.play();
        assertEquals(game.getResult(), Result.WIN);
    }
    @Test public void testLowercaseSecretGuessUppercase() {
        SecretWord secret = new SecretWord("phone");
        TestGuesser guesser = new TestGuesser("PHONE");
        Game game = new Game(secret, guesser);
        game.play();
        assertEquals(game.getResult(), Result.WIN);
    }
 
    @Test public void testRepeatedGuess() {
        SecretWord secret = new SecretWord("phone");
        TestGuesser guesser = new TestGuesser("aaaaaaaaphone");
        Game game = new Game(secret, guesser);
        game.setErrorLimit(2);
        game.play();
        assertEquals(game.getResult(), Result.WIN);
    }
   
    @Test public void testRepeatedGuessLowerUpper() {
        SecretWord secret = new SecretWord("phone");
        TestGuesser guesser = new TestGuesser("aAAAAAAAphone");
        Game game = new Game(secret, guesser);
        game.setErrorLimit(2);
        game.play();
        assertEquals(game.getResult(), Result.WIN);
    }
    @Test public void testRepeatedGuessUpperLower() {
        SecretWord secret = new SecretWord("phone");
        TestGuesser guesser = new TestGuesser("Aaaaaaaaaphone");
        Game game = new Game(secret, guesser);
        game.setErrorLimit(2);
        game.play();
        assertEquals(game.getResult(), Result.WIN);
    }
}
