/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package triangle;
import triangle.view.UserInterface;
public class App {

    public static void main(String[] args) {
       UserInterface ui = new UserInterface();
    }
}
