/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package DiceRoll.view;
import DiceRoll.model.Dice;

import javax.swing.*;
import java.awt.event.*;
import java.util.Random;
import java.awt.*;

public class DiceRollGUI implements ActionListener
{
    
    JFrame mainFrame;
    JPanel mainPanel, panel2;
    Dice dice;
    Random rand = new Random();
    JButton all;

    public DiceRollGUI (Dice dice)
    {
        this.dice = dice;
        this.mainFrame = new JFrame("DICE ROLL GAME");
        this.mainFrame.setLayout(new BorderLayout());
        this.mainFrame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.mainFrame.setResizable(false);


        this.mainPanel = new JPanel();
        this.mainPanel.setBackground(Color.cyan);

        this.dice = new Dice(this);
        
        this.all = new JButton("Roll all");
        this.all.setFocusable(false);
        this.all.setFont(new Font("Times New Roman",0,30));
        this.all.addActionListener(this);
        this.panel2 =new JPanel();
        this.panel2.setBackground(Color.cyan);
        
        this.mainPanel.add(this.dice);
        this.panel2.add(this.all);
        
        
        this.mainFrame.add(mainPanel);
        this.mainFrame.add(panel2,BorderLayout.SOUTH);
        this.mainFrame.pack();
        this.mainFrame.setVisible(true);

    }

    @Override
    public void actionPerformed(ActionEvent event)
    {
        
        for (int i = 0; i<3; i++)
        {
        if(event.getSource()== this.dice.buttons[i])
        {
            int value = rand.nextInt(6)+1;
            this.dice.buttons[i].setText(""+dice.DiceFaceValue(value));
            this.dice.buttons[i].setFont(new Font(null,Font.BOLD,80));
            
        }
        else if (event.getSource() == this.all)
        {
            int value = rand.nextInt(6)+1;
            this.dice.buttons[i].setText(this.dice.DiceFaceValue(value));
            this.dice.buttons[i].setFont(new Font(null,Font.BOLD, 80));
        }
        }
        
    }
    

}


