/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package mini_project;
import javax.swing.*;
import mini_project.model.BarShape;
import mini_project.model.HShape;
import mini_project.model.LShape;
import mini_project.model.Square;
import mini_project.view.Barpanel;
import mini_project.view.HPanel;
import mini_project.view.Squarepanel;
import mini_project.view.ShapePanel;
import mini_project.controller.ShapeController;


public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        JFrame frame = new JFrame();
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        
        LShape lShape = new LShape();

        BarShape bShape = new BarShape();
        HShape hShape = new HShape();
        Square sShape = new Square();
        
        frame.addKeyListener(new ShapeController(lShape));
        frame.addKeyListener(new ShapeController(bShape));
        frame.addKeyListener(new ShapeController(hShape));
        frame.addKeyListener(new ShapeController(sShape));
        
        JPanel mainPanel = new JPanel();
        mainPanel.add(new ShapePanel(lShape));
        mainPanel.add(new ShapePanel(bShape));
        mainPanel.add(new ShapePanel(hShape));
        mainPanel.add(new ShapePanel(sShape));        

        frame.add(mainPanel);
        frame.pack();
        frame.setVisible(true);
    }
}
