/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package wordgame;

import org.junit.Test;
import static org.junit.Assert.*;

import wordgame.model.SecretWord;

public class GameTest {
    @Test public void playToWin() {
        SecretWord secret = new SecretWord("mouse");
        TestGuesser guesser = new TestGuesser("mouse");
        Game game = new Game(secret, guesser);
        game.play();
        assertEquals(game.getResult(), Result.WIN);
    }

    @Test public void playToLose() {
        SecretWord secret = new SecretWord("mouse");
        TestGuesser guesser = new TestGuesser("abcdf");
        Game game = new Game(secret, guesser);
        game.play();
        assertEquals(game.getResult(), Result.LOSE);
    }

    @Test public void errorLimitTestLose() {
        SecretWord secret = new SecretWord("mouse");
        TestGuesser guesser = new TestGuesser("abcdfgmouse");
        Game game = new Game(secret, guesser);
        game.setErrorLimit(6);
        game.play();
        assertEquals(game.getResult(), Result.LOSE);
    }

    @Test public void errorLimitTestWin() {
        SecretWord secret = new SecretWord("hello");
        TestGuesser guesser = new TestGuesser("abcdfghelo");
        Game game = new Game(secret, guesser);
        game.setErrorLimit(7);
        game.play();
        assertEquals(game.getResult(), Result.WIN);
    }
    @Test public void testCaseSensitiveLose() {
        SecretWord secret = new SecretWord("HeLlO");
        TestGuesser guesser = new TestGuesser("helO");
        Game game = new Game(secret, guesser);
        game.play();
        assertEquals(game.getResult(), Result.LOSE);
    }
    @Test public void testCaseSensitiveWin() {
        SecretWord secret = new SecretWord("HeLlO");
        TestGuesser guesser = new TestGuesser("HeLlO");
        Game game = new Game(secret, guesser);
        game.play();
        assertEquals(game.getResult(), Result.WIN);
    }

}
