/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package mini_project;

import javax.swing.*;

import mini_project.model.*;
import mini_project.view.FieldPanel;
import mini_project.controller.ShapeController;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void addShapeToBottom(Field field){
       LShape shape = new LShape();
       field.addShape(shape, 7, 8);
       field.mergeFlyingShape();
    }

    public static void main(String[] args) {
        JFrame frame = new JFrame();
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);        
        JPanel mainPanel = new JPanel();

        Field field = new Field(10, 20);
        SmallStickShape stick = new SmallStickShape();
        stick.rotateLeft();
        field.addShape(stick, 8, 5);
        field.mergeFlyingShape();

        LShape lShape = new LShape();
        frame.addKeyListener(new ShapeController(lShape));
        field.addShape(lShape, 0, 5);
        mainPanel.add(new FieldPanel(field));

        
        frame.add(mainPanel);
        frame.pack();
        frame.setVisible(true);

        addShapeToBottom(field);
    }
}
