/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package helloFromGradle;

public class Driver {
    public String getGreeting() {
        return "Hello from Gradle!";
    }

    public static void main(String[] args) {
        System.out.println(new Driver().getGreeting());
    }
}
