/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package wordgame;

import java.io.IOException;
import java.util.ArrayList;
import java.util.Random;

import wordgame.model.SecretWord;
import wordgame.controller.Controller;


public class App {
    public static String pickWord(String fileName) throws IOException
    {
        Dictionary dictionary = new Dictionary(fileName);
        ArrayList<String> allWords = dictionary.getWords();
        Random randomizer = new Random();
        int randomLocation = randomizer.nextInt(allWords.size());
        return allWords.get(randomLocation);
    }

    public static void main(String[] args) {
        if (args.length == 0){
            System.out.println("Please provide a file with words");
            return;
        }
        SecretWord secretWord = null;
        try{
            secretWord = new SecretWord(pickWord(args[0]));
        }
        catch(IOException e){
            System.out.println(e.getMessage());
            return;
        }

        
        Controller control = new Controller(secretWord);
    }
}
